Restructure menus and add menu wheel support
Panzerschrek/Chasm-Reverse pull request #54
Opened 2023-04-14 17:05 UTC by jopadan

Move all standard ProcessEvent of  derived classes to MenuBase and add Up(), Down(), Left(), Right(), Select(), Back() and CharInput(). Support mouse wheel in MenuBase::ProcessEvent and key code selection using in_set_mode along with CharInput.
All standard events are now in MenuBase. Derived  classes use abstract virtual override functions listed above.

2023-04-15 12:05 UTC, Panzerschrek requested changes

2023-04-15 12:05 UTC, Panzerschrek commented on src/menu.cpp
> +								if( !host_commands_.CurrentMap() )
It's not clear for me, why do you need to check current map. Please, explain.

2023-04-15 12:05 UTC, Panzerschrek commented on src/menu.cpp
> +							}
This looks like copy-paste. Please, move enter/mouse click processing code into separate function.

2023-04-15 12:05 UTC, Panzerschrek commented on src/menu.cpp
> +								if( !host_commands_.CurrentMap() )
Avoid implicit casts to bool (for better readability and errors prevention). Compare pointers explicitly against `nullptr`.

2023-04-15 12:17 UTC, Panzerschrek commented
I tried this.
Mouse wheel navigation seems to be ok. But mouse button menu selection seems to be confusing. Normally, this should work together with menu selection via mouse cursor (like, for example, in Quake III Arena). But PanzerChasm menu (and original menu) doesn't work this way.

2023-04-15 12:44 UTC, jopadan commented on src/menu.cpp
> +								if( !host_commands_.CurrentMap() )
A map is set if the game is running in FPS HUD Level draw mode and a menu is not open

2023-04-15 12:51 UTC, jopadan commented on src/menu.cpp
> +							}
This menu is Menu not MenuBase based.
I just switched to switch for now.

2023-04-15 13:03 UTC, jopadan commented
I'll add ControlsMenu::KeySettings reconfigurable mixed mouse with wheel and keyboard support soon

2023-04-15 15:19 UTC, Panzerschrek approved these changes

2023-04-16 15:46 UTC, jopadan commented on src/menu.cpp
> +							}
It might be better to use getMapLoader to get the current map I need to explore it first.

2023-04-16 18:53 UTC, merged